[package]
name = "rsk-simulation"
version = "0.1.0"
edition = "2021"

[features]
gui = ["dep:bevy"]
default = ["gui"]

[dependencies]
rapier2d = { version = "0.18.0", features = [
    "simd-stable"
] }
bevy = { version = "*", optional = true }